services:
  proxy:
    container_name: "proxy"
    build:
      context: .
      target: proxy
    tty: true
    env_file:
      - .env

  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    tty: true
    env_file:
      - .env
  
  cache:
    container_name: cache
    image: eqalpha/keydb:alpine
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - cache-data:/data
      - ./config/cache/keydb.conf:/etc/keydb/keydb.conf
  
  database:
    container_name: database
    image: postgres:alpine
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  cache-data:
  database-data: